### ISSUE TITLE
Example uses hardcoded display name and has comment about getting userId from session, but randomly generates it every request

### ISSUE THREAD

**Issue by mattmazzola** [passwordless/passwordless-nodejs-example#3]
In the NodeJS example

The implementation of the /create-token route has some suspicious code.
The two lines referenced here
https://github.com/passwordless/passwordless-nodejs-example/blob/cde07b112a93a86027062687792c24618672f3d5/app.js#L37-L38

## Issues

1. displayName
The value of the `displayName` is hard code, but this display name seems like it should be assigned the value of the alias or perhaps take in alternate value from the request.query.

1. The comment says it should get userId from session or cookie, but yet it is a randomly generated id on each request.

## Solutions

1. If this code is used for passwordless dev server, does this hardcoded value imply that display name does not matter?

1. Perhaps the comment is stale or irrelevant. When creating a token is does seem appropriate to generate a new userId to be associated with the token

**Comment by mattmazzola** [comment]
I noticed the display name shows up in the Windows prompt for the users key.
![image](https://user-images.githubusercontent.com/2856501/198849489-d9994780-e3d8-4a40-9070-7a1e2b9399e2.png)

Given the sample code has "Mr Guest" hardcoded but the image above shows "Mr Guest Suspicious Produce" then it would seem the demo server concatenates random string onto the hardcoded alias. I assume this would make EACH attempt to Registration have a unique username (since displayname was set to username)

**Comment by abergs** [comment]
Fixed in the latest versions of this sample.
