### ISSUE TITLE
The comment for sample /create-token route is misleading

### ISSUE THREAD

**Issue by mattmazzola** [passwordless/passwordless-nodejs-example#4]
The comment says

```
  * Request body looks like: 
  * { UserID: '12345', displayName:'Anders Åberg'} 
```
However, the actual body of the request constructed below uses `userId` (not `UserID`) and `displayname` (not `displayName`)

This is misleading and may cause people to construct the WRONG request body. 

https://github.com/passwordless/passwordless-nodejs-example/blob/cde07b112a93a86027062687792c24618672f3d5/app.js#L28-L44

Also the API documentation here shows `displayName` is actually correct, which means the sample using `displayname` is incorrect?

https://docs.passwordless.dev/guide/operations.html#register-create-token

**Comment by abergs** [comment]
@mattmazzola Sorry for taking so long to get back to you on this issue! I would love to help you use passwordless, and I think we can do make this sample better.

For example, we now have a NodeJS SDK that might make things easier: https://docs.passwordless.dev/guide/backend/nodejs.html
