### ISSUE TITLE
Sign-In response using demo server has userId not username

### ISSUE THREAD

**Issue by mattmazzola** [passwordless/passwordless-nodejs-example#5]
Based on the API documentation here:
https://docs.passwordless.dev/guide/operations.html#sign-in-verify-token

Applications would want a unique identifier for the user AND something they recognize such as their name.
However, the documentation shows the response with
```
"username": "anders@user.com",
"nickname": null,
```

When I actually test the demo server I get a response with
```
"userId": "726924396"
"nickname": null
```
From this difference there are multiple questions:

1. How do we set nickname?
1. Should the documentation show `userId` being set?
1. Should the API return a `username` property with the response? (Which seems to overlap with nickname)

**Comment by abergs** [comment]
Hey @mattmazzola, this has all been updated for v4.
